# Generated by Django 4.1.3 on 2023-01-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=15)),
                ('Discription', models.TextField()),
                ('time_taken', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
