# Generated by Django 4.1.3 on 2023-01-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('rating', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('pic', models.FileField(default=None, max_length=1000, null=True, upload_to='Home/')),
            ],
        ),
        migrations.CreateModel(
            name='Product3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('rating', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('pic', models.FileField(default=None, max_length=1000, null=True, upload_to='Home/')),
            ],
        ),
    ]
