# Generated by Django 4.1.3 on 2023-01-29 09:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_product2_product3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='product',
            name='Text',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product2',
            name='Text',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product3',
            name='Text3',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
