# Generated by Django 4.1.3 on 2023-01-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_contact_time_taken_product_text_product2_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pic',
            new_name='pic1',
        ),
        migrations.RenameField(
            model_name='product2',
            old_name='pic',
            new_name='pic1',
        ),
        migrations.RenameField(
            model_name='product3',
            old_name='pic',
            new_name='pic1',
        ),
        migrations.AddField(
            model_name='product',
            name='pic2',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='Home/'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic3',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='Home/'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic4',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='Home/'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic5',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='Home/'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic6',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='Home/'),
        ),
        migrations.AddField(
            model_name='product2',
            name='pic2',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='Home/'),
        ),
        migrations.AddField(
            model_name='product2',
            name='pic3',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='Home/'),
        ),
        migrations.AddField(
            model_name='product2',
            name='pic4',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='Home/'),
        ),
        migrations.AddField(
            model_name='product2',
            name='pic5',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='Home/'),
        ),
        migrations.AddField(
            model_name='product2',
            name='pic6',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='Home/'),
        ),
        migrations.AddField(
            model_name='product3',
            name='pic2',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='Home/'),
        ),
        migrations.AddField(
            model_name='product3',
            name='pic3',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='Home/'),
        ),
        migrations.AddField(
            model_name='product3',
            name='pic4',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='Home/'),
        ),
        migrations.AddField(
            model_name='product3',
            name='pic5',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='Home/'),
        ),
        migrations.AddField(
            model_name='product3',
            name='pic6',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='Home/'),
        ),
    ]
